/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "boost.browser-logs": [],
    "sanctum.csrf-cookie": [],
    "dashboard": [],
    "accounts.index": [],
    "accounts.create": [],
    "accounts.store": [],
    "accounts.edit": [
        {
            "name": "account",
            "required": true,
            "binding": "id"
        }
    ],
    "accounts.update": [
        {
            "name": "account",
            "required": true,
            "binding": "id"
        }
    ],
    "accounts.destroy": [
        {
            "name": "account",
            "required": true,
            "binding": "id"
        }
    ],
    "categories.index": [],
    "categories.create": [],
    "categories.store": [],
    "categories.edit": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "categories.update": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "categories.destroy": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "budgets.index": [],
    "budgets.create": [],
    "budgets.store": [],
    "budgets.edit": [
        {
            "name": "budget",
            "required": true,
            "binding": "id"
        }
    ],
    "budgets.update": [
        {
            "name": "budget",
            "required": true,
            "binding": "id"
        }
    ],
    "budgets.destroy": [
        {
            "name": "budget",
            "required": true,
            "binding": "id"
        }
    ],
    "transactions.index": [],
    "transactions.create": [],
    "transactions.store": [],
    "transactions.edit": [
        {
            "name": "transaction",
            "required": true,
            "binding": "id"
        }
    ],
    "transactions.update": [
        {
            "name": "transaction",
            "required": true,
            "binding": "id"
        }
    ],
    "transactions.destroy": [
        {
            "name": "transaction",
            "required": true,
            "binding": "id"
        }
    ],
    "portfolios.index": [],
    "portfolios.create": [],
    "portfolios.store": [],
    "portfolios.show": [
        {
            "name": "portfolio",
            "required": true,
            "binding": "id"
        }
    ],
    "portfolios.edit": [
        {
            "name": "portfolio",
            "required": true,
            "binding": "id"
        }
    ],
    "portfolios.update": [
        {
            "name": "portfolio",
            "required": true,
            "binding": "id"
        }
    ],
    "portfolios.destroy": [
        {
            "name": "portfolio",
            "required": true,
            "binding": "id"
        }
    ],
    "assets.index": [],
    "assets.create": [],
    "assets.store": [],
    "investment-transactions.create": [
        {
            "name": "portfolio",
            "required": true,
            "binding": "id"
        }
    ],
    "investment-transactions.store": [
        {
            "name": "portfolio",
            "required": true,
            "binding": "id"
        }
    ],
    "investment-transactions.edit": [
        {
            "name": "investment_transaction",
            "required": true
        }
    ],
    "investment-transactions.update": [
        {
            "name": "investment_transaction",
            "required": true
        }
    ],
    "investment-transactions.destroy": [
        {
            "name": "investment_transaction",
            "required": true
        }
    ],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "verification.notice": [],
    "verification.verify": [
        {
            "name": "id",
            "required": true
        },
        {
            "name": "hash",
            "required": true
        }
    ],
    "verification.send": [],
    "password.confirm": [],
    "password.update": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
