/* This file is generated by Ziggy. */
declare module 'ziggy-js' {
  interface RouteList {
    "boost.browser-logs": [],
    "sanctum.csrf-cookie": [],
    "ready": [],
    "dashboard": [],
    "reports.index": [],
    "reports.transactions.export": [],
    "imports.index": [],
    "imports.template": [
        {
            "name": "kind",
            "required": true
        }
    ],
    "imports.store": [],
    "imports.show": [
        {
            "name": "importBatch",
            "required": true,
            "binding": "public_id"
        }
    ],
    "imports.confirm": [
        {
            "name": "importBatch",
            "required": true,
            "binding": "public_id"
        }
    ],
    "imports.destroy": [
        {
            "name": "importBatch",
            "required": true,
            "binding": "public_id"
        }
    ],
    "reconciliations.index": [],
    "reconciliations.template": [],
    "reconciliations.store": [],
    "reconciliations.show": [
        {
            "name": "reconciliation",
            "required": true,
            "binding": "public_id"
        }
    ],
    "reconciliations.confirm": [
        {
            "name": "reconciliation",
            "required": true,
            "binding": "public_id"
        }
    ],
    "reconciliations.destroy": [
        {
            "name": "reconciliation",
            "required": true,
            "binding": "public_id"
        }
    ],
    "accounts.index": [],
    "accounts.create": [],
    "accounts.store": [],
    "accounts.edit": [
        {
            "name": "account",
            "required": true,
            "binding": "id"
        }
    ],
    "accounts.update": [
        {
            "name": "account",
            "required": true,
            "binding": "id"
        }
    ],
    "accounts.destroy": [
        {
            "name": "account",
            "required": true,
            "binding": "id"
        }
    ],
    "categories.index": [],
    "categories.create": [],
    "categories.store": [],
    "categories.show": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "categories.edit": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "categories.update": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "categories.destroy": [
        {
            "name": "category",
            "required": true,
            "binding": "id"
        }
    ],
    "budgets.index": [],
    "budgets.create": [],
    "budgets.store": [],
    "budgets.edit": [
        {
            "name": "budget",
            "required": true,
            "binding": "id"
        }
    ],
    "budgets.update": [
        {
            "name": "budget",
            "required": true,
            "binding": "id"
        }
    ],
    "budgets.destroy": [
        {
            "name": "budget",
            "required": true,
            "binding": "id"
        }
    ],
    "goals.index": [],
    "goals.create": [],
    "goals.store": [],
    "goals.edit": [
        {
            "name": "goal",
            "required": true,
            "binding": "id"
        }
    ],
    "goals.update": [
        {
            "name": "goal",
            "required": true,
            "binding": "id"
        }
    ],
    "goals.destroy": [
        {
            "name": "goal",
            "required": true,
            "binding": "id"
        }
    ],
    "transactions.index": [],
    "transactions.create": [],
    "transactions.store": [],
    "transactions.edit": [
        {
            "name": "transaction",
            "required": true,
            "binding": "id"
        }
    ],
    "transactions.update": [
        {
            "name": "transaction",
            "required": true,
            "binding": "id"
        }
    ],
    "transactions.destroy": [
        {
            "name": "transaction",
            "required": true,
            "binding": "id"
        }
    ],
    "agenda.index": [],
    "recurring.index": [],
    "recurring.create": [],
    "recurring.store": [],
    "recurring.edit": [
        {
            "name": "recurring",
            "required": true,
            "binding": "id"
        }
    ],
    "recurring.update": [
        {
            "name": "recurring",
            "required": true,
            "binding": "id"
        }
    ],
    "recurring.destroy": [
        {
            "name": "recurring",
            "required": true,
            "binding": "id"
        }
    ],
    "installments.index": [],
    "installments.create": [],
    "installments.store": [],
    "installments.destroy": [
        {
            "name": "installment",
            "required": true,
            "binding": "id"
        }
    ],
    "portfolios.operations.export": [
        {
            "name": "portfolio",
            "required": true,
            "binding": "id"
        }
    ],
    "portfolios.index": [],
    "portfolios.create": [],
    "portfolios.store": [],
    "portfolios.show": [
        {
            "name": "portfolio",
            "required": true,
            "binding": "id"
        }
    ],
    "portfolios.edit": [
        {
            "name": "portfolio",
            "required": true,
            "binding": "id"
        }
    ],
    "portfolios.update": [
        {
            "name": "portfolio",
            "required": true,
            "binding": "id"
        }
    ],
    "portfolios.destroy": [
        {
            "name": "portfolio",
            "required": true,
            "binding": "id"
        }
    ],
    "assets.index": [],
    "assets.create": [],
    "assets.store": [],
    "brokers.index": [],
    "brokers.create": [],
    "brokers.store": [],
    "brokers.edit": [
        {
            "name": "broker",
            "required": true,
            "binding": "id"
        }
    ],
    "brokers.update": [
        {
            "name": "broker",
            "required": true,
            "binding": "id"
        }
    ],
    "assets.refresh": [
        {
            "name": "asset",
            "required": true,
            "binding": "id"
        }
    ],
    "investment-transactions.create": [
        {
            "name": "portfolio",
            "required": true,
            "binding": "id"
        }
    ],
    "investment-transactions.store": [
        {
            "name": "portfolio",
            "required": true,
            "binding": "id"
        }
    ],
    "investment-transactions.edit": [
        {
            "name": "investment_transaction",
            "required": true
        }
    ],
    "investment-transactions.update": [
        {
            "name": "investment_transaction",
            "required": true
        }
    ],
    "investment-transactions.destroy": [
        {
            "name": "investment_transaction",
            "required": true
        }
    ],
    "profile.edit": [],
    "profile.update": [],
    "profile.destroy": [],
    "register": [],
    "login": [],
    "password.request": [],
    "password.email": [],
    "password.reset": [
        {
            "name": "token",
            "required": true
        }
    ],
    "password.store": [],
    "password.confirm": [],
    "password.update": [],
    "logout": [],
    "storage.local": [
        {
            "name": "path",
            "required": true
        }
    ],
    "storage.local.upload": [
        {
            "name": "path",
            "required": true
        }
    ]
}
}
export {};
